# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DepTree < Formula
  desc ""
  homepage "https://github.com/gabotechs/dep-tree"
  version "0.11.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.11.8/dep-tree_0.11.8_Darwin_x86_64.tar.gz"
      sha256 "1eacc3f5cafc403dbe027e238b88dd1f1b4d2b1bc9f5e89b3c7d3d88b3a82247"

      def install
        bin.install "dep-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.11.8/dep-tree_0.11.8_Darwin_arm64.tar.gz"
      sha256 "f58ff10cfd2c23249218b499c8b2196dab3c306a2c8de60cb528ba3e4660a7da"

      def install
        bin.install "dep-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.11.8/dep-tree_0.11.8_Linux_arm64.tar.gz"
      sha256 "45422a9a078c647affd62cb07537074e0e8d4c9c08a58ea4cbbd8174057ca206"

      def install
        bin.install "dep-tree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.11.8/dep-tree_0.11.8_Linux_x86_64.tar.gz"
      sha256 "4183460710b9db23625adcff6935593d5430443d0baa5f33196aa5aaf17b04b7"

      def install
        bin.install "dep-tree"
      end
    end
  end
end
