# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DepTree < Formula
  desc ""
  homepage "https://github.com/gabotechs/dep-tree"
  version "0.22.1"

  on_macos do
    on_intel do
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.22.1/dep-tree_0.22.1_darwin_amd64.tar.gz"
      sha256 "6202c65d0830f1f991e5577d5c3b6f0acec3887a207c6a63c92fd53ef7db7fa7"

      def install
        bin.install "dep-tree"
      end
    end
    on_arm do
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.22.1/dep-tree_0.22.1_darwin_arm64.tar.gz"
      sha256 "bf58228855025231d6f3460ce536fd7ae8ebd0bfcc721a4c149d458f05e239c0"

      def install
        bin.install "dep-tree"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/dep-tree/releases/download/v0.22.1/dep-tree_0.22.1_linux_amd64.tar.gz"
        sha256 "00418b1b8529a55291dfb1e27f9209a73b4e8f5e7fef27fd411f6148acc735c3"

        def install
          bin.install "dep-tree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/dep-tree/releases/download/v0.22.1/dep-tree_0.22.1_linux_arm64.tar.gz"
        sha256 "fe3c38f07cc2f27afa2fc4da8d8a2e8fa258d89f614ba86d9078a11ee8ca551d"

        def install
          bin.install "dep-tree"
        end
      end
    end
  end
end
