# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DepTree < Formula
  desc ""
  homepage "https://github.com/gabotechs/dep-tree"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.15.1/dep-tree_0.15.1_darwin_amd64.tar.gz"
      sha256 "0a2da4d4a37106dbd227d11e0399e1c740531c756cf071f7d2e87d532a8941c4"

      def install
        bin.install "dep-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.15.1/dep-tree_0.15.1_darwin_arm64.tar.gz"
      sha256 "46de57bb1396656e8825ebaeb2ecf78fb242c59fe4afc7df87fbb64b35abfac5"

      def install
        bin.install "dep-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.15.1/dep-tree_0.15.1_linux_arm64.tar.gz"
      sha256 "246845021d3d9d73552f20f7f75ef62abd80d7afe8b83ec9c41f27bec72d734d"

      def install
        bin.install "dep-tree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/dep-tree/releases/download/v0.15.1/dep-tree_0.15.1_linux_amd64.tar.gz"
      sha256 "08fadc429ad7b8f94158a4a7dd67fe19a02a94be557857c0ed31a5fd59d5a380"

      def install
        bin.install "dep-tree"
      end
    end
  end
end
