# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstraitViz < Formula
  desc ""
  homepage "https://github.com/gabotechs/substrait-viz"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.10/substrait-viz_Darwin_x86_64.tar.gz"
      sha256 "4b0302630648fd8f5a8252df0ce3a82cc7fc387de12da1e8b7046a267528f6e0"

      def install
        bin.install "substrait-viz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.10/substrait-viz_Darwin_arm64.tar.gz"
      sha256 "48b88ccfe66ed2e1b0193ea49b99fe7242b941243a57897636dc14c9521d72c1"

      def install
        bin.install "substrait-viz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.10/substrait-viz_Linux_x86_64.tar.gz"
        sha256 "7f36cecb1e7a4c32e9436aa1ab9fb1dcbc09e35c7a3b929ce7637bb68d21e674"

        def install
          bin.install "substrait-viz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.10/substrait-viz_Linux_arm64.tar.gz"
        sha256 "126a5295b37d5ee545334431ffe9631a6072532fa6b5768cc428ba011b70f8b5"

        def install
          bin.install "substrait-viz"
        end
      end
    end
  end
end
