# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstraitViz < Formula
  desc ""
  homepage "https://github.com/gabotechs/substrait-viz"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.5/substrait-viz_Darwin_x86_64.tar.gz"
      sha256 "93bd44cbcbc1acfe0ace43fcf0ceb47e718d587da51ccf69a95533e9d499c99c"

      def install
        bin.install "substrait-viz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.5/substrait-viz_Darwin_arm64.tar.gz"
      sha256 "b8646defdabc93bc35e5aa3427307c6a6a7a5fdb5a916ccbb37c1d1f81cc9656"

      def install
        bin.install "substrait-viz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.5/substrait-viz_Linux_x86_64.tar.gz"
        sha256 "813a95c0b3216b25723782d5a45d5265b7a9fafd04a6891738db9e457a97cc95"

        def install
          bin.install "substrait-viz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabotechs/substrait-viz/releases/download/v0.0.5/substrait-viz_Linux_arm64.tar.gz"
        sha256 "4729d345a3d070bb24ac345b8fd8f4f42a2ac3c4e755e000c1f20295cdf128d5"

        def install
          bin.install "substrait-viz"
        end
      end
    end
  end
end
